package com.chenxu.workassistant.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.chenxu.workassistant.dao.CollectionEntity;
import com.chenxu.workassistant.dao.HistoryEntity;
import com.chenxu.workassistant.dao.EnclosureEntity;

import com.chenxu.workassistant.dao.CollectionEntityDao;
import com.chenxu.workassistant.dao.HistoryEntityDao;
import com.chenxu.workassistant.dao.EnclosureEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig collectionEntityDaoConfig;
    private final DaoConfig historyEntityDaoConfig;
    private final DaoConfig enclosureEntityDaoConfig;

    private final CollectionEntityDao collectionEntityDao;
    private final HistoryEntityDao historyEntityDao;
    private final EnclosureEntityDao enclosureEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        collectionEntityDaoConfig = daoConfigMap.get(CollectionEntityDao.class).clone();
        collectionEntityDaoConfig.initIdentityScope(type);

        historyEntityDaoConfig = daoConfigMap.get(HistoryEntityDao.class).clone();
        historyEntityDaoConfig.initIdentityScope(type);

        enclosureEntityDaoConfig = daoConfigMap.get(EnclosureEntityDao.class).clone();
        enclosureEntityDaoConfig.initIdentityScope(type);

        collectionEntityDao = new CollectionEntityDao(collectionEntityDaoConfig, this);
        historyEntityDao = new HistoryEntityDao(historyEntityDaoConfig, this);
        enclosureEntityDao = new EnclosureEntityDao(enclosureEntityDaoConfig, this);

        registerDao(CollectionEntity.class, collectionEntityDao);
        registerDao(HistoryEntity.class, historyEntityDao);
        registerDao(EnclosureEntity.class, enclosureEntityDao);
    }
    
    public void clear() {
        collectionEntityDaoConfig.clearIdentityScope();
        historyEntityDaoConfig.clearIdentityScope();
        enclosureEntityDaoConfig.clearIdentityScope();
    }

    public CollectionEntityDao getCollectionEntityDao() {
        return collectionEntityDao;
    }

    public HistoryEntityDao getHistoryEntityDao() {
        return historyEntityDao;
    }

    public EnclosureEntityDao getEnclosureEntityDao() {
        return enclosureEntityDao;
    }

}
